const data = [
  "aa aa aa aa",
  "ss ss ss ss",
  "dd dd dd dd",
  "ff ff ff ff",
  "gg gg gg gg",
  "hh hh hh hh",
  "jj jj jj jj",
  "kk kk kk kk",
  "ll ll ll ll",
  ";; ;; ;; ;;",
  "ls dj al dl",
  "as as as as",
  "df df df df",
  "gh gh gh gh",
  "jk jk jk jk",
  "l; l; l; l;",
  "sa df gj lk",
  "dj al sk ;l",
  "as df gj kl",
  "sd jg la ;k",
  "asdf l;l;",
  "djsa fghl",
  "sadj hgfl",
  "jdas l;gh",
  "asdj ;lgf",
  "sdja hl;g",
  "djsa lg;h",
  "adsj ;flg",
  "sjad glh;",
  "jads ;lhg",
  "dsafadsfas",
  "adsfadsfas",
];

export default data;
